version: '3.8'

services:
  # Aplicação Node.js
  app:
    build: .
    container_name: blog-aulas-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/blog-aulas
      - PORT=3000
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - blog-network

  # Banco de dados MongoDB
  mongodb:
    image: mongo:7.0
    container_name: blog-aulas-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blog-aulas
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    networks:
      - blog-network

  # Interface web para MongoDB
  mongo-express:
    image: mongo-express:1.0.0
    container_name: blog-aulas-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - blog-network

# Volumes persistentes
volumes:
  mongodb_data:
    driver: local

# Rede para comunicação entre containers
networks:
  blog-network:
    driver: bridge
